#!/usr/bin/env python3
"""Recompute calibrated pose columns after manual edits to *_cam points.

This intentionally does not use cv2.aruco. It consumes calibration artifacts
that were already generated by the Arena calibration workflow.
"""

import argparse
import json
import math
import pickle
import re
from datetime import datetime
from pathlib import Path
from typing import Callable, Dict, Optional, Tuple

import cv2
import numpy as np
import pandas as pd


DATE_FORMAT = "%Y%m%dT%H%M%S"
DEFAULT_APP_CALIBRATION_DIR = None


class CalibrationError(Exception):
    pass


def parse_video_info(video_path: str) -> Tuple[str, Optional[str]]:
    match = re.match(r"(.+?)_(\d{8}T\d{6})", Path(video_path).stem)
    if not match:
        return "top", None
    return match.group(1), match.group(2)


def get_last_artifact(search_folder: Path, cache_prefix: str, image_date: Optional[str] = None) -> Optional[Path]:
    image_dt = datetime.strptime(image_date, DATE_FORMAT) if image_date else None
    last_dt = None
    last_path = None
    for path in search_folder.glob(f"{cache_prefix}*.pkl"):
        try:
            artifact_dt = datetime.strptime(path.stem.split("_")[-1], DATE_FORMAT)
        except ValueError:
            continue
        if image_dt is not None and artifact_dt > image_dt:
            continue
        if last_dt is None or artifact_dt > last_dt:
            last_dt = artifact_dt
            last_path = path
    return last_path


class CharucoCalibration:
    def __init__(self, calib_dir: str, cam_name: str):
        self.calib_dir = Path(calib_dir).expanduser()
        self.cam_name = cam_name
        self.undistort_dir = self.calib_dir / "undistortion" / cam_name
        self.real_world_dir = self.calib_dir / "real_world" / cam_name
        self.mtx = None
        self.dist = None
        self.new_camera_mtx = None
        self.homography = None

    def init(self, image_date: Optional[str]):
        undistort_path = get_last_artifact(
            self.undistort_dir,
            f"undistortion_{json.dumps(None)}",
            image_date,
        )
        transform_path = get_last_artifact(
            self.real_world_dir,
            f"aruco_transformation_{json.dumps(None)}",
            image_date,
        )
        if not undistort_path or not transform_path:
            raise CalibrationError(f"Missing calibration artifacts for {self.cam_name} in {self.calib_dir}")

        with undistort_path.open("rb") as f:
            params = pickle.load(f)
        with transform_path.open("rb") as f:
            transform = pickle.load(f)

        self.mtx = params["mtx"]
        self.dist = params["dist"]
        w, h = params["w"], params["h"]
        self.new_camera_mtx, _ = cv2.getOptimalNewCameraMatrix(self.mtx, self.dist, (w, h), 1, (w, h))
        self.homography = transform["homography"]
        return undistort_path, transform_path

    def get_location(self, frame_x: float, frame_y: float) -> Tuple[float, float]:
        uv = cv2.undistortPoints(
            np.array([frame_x, frame_y]).astype("float32"),
            self.mtx,
            self.dist,
            None,
            self.new_camera_mtx,
        ).ravel()
        uv_1 = np.array([[uv[0], uv[1], 1]], dtype=np.float32).T
        result = np.dot(self.homography, uv_1).ravel()
        return float(result[0] / result[2]), float(result[1] / result[2])


def calc_head_angle(row: pd.Series, prefix: str = "") -> float:
    needed = [
        f"{prefix}nose_x", f"{prefix}nose_y",
        f"{prefix}left_ear_x", f"{prefix}left_ear_y",
        f"{prefix}right_ear_x", f"{prefix}right_ear_y",
    ]
    if any(col not in row.index or pd.isna(row[col]) for col in needed):
        return np.nan
    x_nose, y_nose = row[f"{prefix}nose_x"], row[f"{prefix}nose_y"]
    x_ears = (row[f"{prefix}right_ear_x"] + row[f"{prefix}left_ear_x"]) / 2
    y_ears = (row[f"{prefix}right_ear_y"] + row[f"{prefix}left_ear_y"]) / 2
    return float(math.atan2(y_ears - y_nose, x_ears - x_nose))


def calc_angle_between_lines(a1: float, b1: float, a2: float, b2: float) -> float:
    return math.atan(abs((a1 * b2 - b1 * a2) / (a1 * a2 + b1 * b2)))


def calc_gaze_deviation_angle(angle: float, bug_x: float, x: float, y: float, screen_y: float) -> float:
    m_exp = (y - screen_y) / (x - bug_x)
    if math.isclose(math.sin(angle), 0):
        x_obs = x
        dev_ang = math.degrees(calc_angle_between_lines(1, 0, m_exp, -1))
    else:
        m_obs = math.sin(angle) / math.cos(angle)
        n_obs = y - m_obs * x
        x_obs = (screen_y - n_obs) / m_obs
        a = math.dist((bug_x, screen_y), (x, y))
        b = math.dist((x_obs, screen_y), (x, y))
        c = abs(x_obs - bug_x)
        try:
            dev_ang = math.degrees(math.acos((a**2 + b**2 - c**2) / (2 * a * b)))
        except ValueError:
            return np.nan
    sign = np.sign(x_obs - bug_x) if angle < math.pi else -np.sign(x_obs - bug_x)
    return float(dev_ang * sign)


def detect_bodyparts(df: pd.DataFrame):
    return sorted(col[:-len("_cam_x")] for col in df.columns if col.endswith("_cam_x"))


def set_col(df: pd.DataFrame, col: str, values) -> int:
    df[col] = values
    return int(pd.Series(values).notna().sum())


def find_bug_pixel_pairs(df: pd.DataFrame):
    pairs = []
    for col in df.columns:
        match = re.fullmatch(r"(bug\d*|bug)_x_?", str(col))
        if not match:
            continue
        prefix = match.group(1)
        suffix = "_" if str(col).endswith("_") else ""
        y_col = f"{prefix}_y{suffix}"
        if y_col in df.columns:
            pairs.append((prefix, str(col), y_col, suffix))
    return pairs


def find_bug_cm_cols(df: pd.DataFrame):
    cols = []
    for col in df.columns:
        match = re.fullmatch(r"(bug\d*|bug)_x_cm_?", str(col))
        if not match:
            continue
        prefix = match.group(1)
        suffix = "_" if str(col).endswith("_") else ""
        cols.append((prefix, str(col), suffix))
    return cols


def update_screen_columns(
    df: pd.DataFrame,
    screen_start_x: Optional[float],
    screen_pix_cm: Optional[float],
    screen_y: Optional[float],
) -> int:
    updated_cells = 0
    if screen_start_x is not None and screen_pix_cm is not None and screen_y is not None:
        for prefix, x_col, y_col, suffix in find_bug_pixel_pairs(df):
            xcm_col = f"{prefix}_x_cm{suffix}"
            ycm_col = f"{prefix}_y_cm{suffix}"
            updated_cells += set_col(df, xcm_col, screen_start_x + df[x_col] * screen_pix_cm)
            updated_cells += set_col(df, ycm_col, screen_y + df[y_col] * screen_pix_cm)

    if screen_y is None or not {"angle_", "x_", "y_"}.issubset(df.columns):
        return updated_cells

    for prefix, bug_x_col, suffix in find_bug_cm_cols(df):
        match = re.fullmatch(r"bug(\d*)", prefix)
        bug_num = match.group(1) if match else ""
        dev_col = f"dev_angle{bug_num}{suffix}"
        values = []
        for _, row in df.iterrows():
            required = [bug_x_col, "angle_", "x_", "y_"]
            if any(pd.isna(row[col]) for col in required):
                values.append(np.nan)
                continue
            values.append(
                calc_gaze_deviation_angle(
                    float(row["angle_"]),
                    float(row[bug_x_col]),
                    float(row["x_"]),
                    float(row["y_"]),
                    float(screen_y),
                )
            )
        updated_cells += set_col(df, dev_col, values)
    return updated_cells


def run_edited_pose_calibration_job(
    pose_file: str,
    video_path: str,
    calibration_dir: str,
    screen_start_x: Optional[float] = None,
    screen_pix_cm: Optional[float] = None,
    screen_y: Optional[float] = None,
    logger: Optional[Callable[[str], None]] = None,
) -> Dict[str, object]:
    log = logger or (lambda message: None)
    if not calibration_dir:
        raise CalibrationError("calibration_dir is required")

    pose_path = Path(pose_file).expanduser()
    cam_name, image_date = parse_video_info(video_path)
    caliber = CharucoCalibration(calibration_dir, cam_name)
    undistort_path, transform_path = caliber.init(image_date)
    log(f"Camera: {cam_name}")
    log(f"Video date: {image_date or 'not parsed'}")
    log(f"Undistortion: {undistort_path}")
    log(f"Real-world transform: {transform_path}")

    is_parquet = pose_path.suffix.lower() == ".parquet"
    df = pd.read_parquet(pose_path) if is_parquet else pd.read_csv(pose_path)

    if "left_ear_cam_x" in df and "right_ear_cam_x" in df:
        df["mid_ears_cam_x"] = df[["left_ear_cam_x", "right_ear_cam_x"]].mean(axis=1)
        df["mid_ears_cam_y"] = df[["left_ear_cam_y", "right_ear_cam_y"]].mean(axis=1)

    bodyparts = detect_bodyparts(df)
    if not bodyparts:
        raise CalibrationError("No *_cam_x columns found in pose file")

    updated_cells = 0
    world_points = {}
    for bodypart in bodyparts:
        x_col = f"{bodypart}_cam_x"
        y_col = f"{bodypart}_cam_y"
        xs = []
        ys = []
        for frame_x, frame_y in zip(df[x_col], df[y_col]):
            if pd.isna(frame_x) or pd.isna(frame_y):
                xs.append(np.nan)
                ys.append(np.nan)
            else:
                x, y = caliber.get_location(float(frame_x), float(frame_y))
                xs.append(x)
                ys.append(y)
        world_points[bodypart] = (pd.Series(xs, index=df.index), pd.Series(ys, index=df.index))

        updated_cells += set_col(df, f"{bodypart}_x", world_points[bodypart][0])
        updated_cells += set_col(df, f"{bodypart}_y", world_points[bodypart][1])

    commit_bodypart = "mid_ears" if "mid_ears" in world_points else bodyparts[0]
    updated_cells += set_col(df, "x_", world_points[commit_bodypart][0])
    updated_cells += set_col(df, "y_", world_points[commit_bodypart][1])

    for col in ["vx_", "vy_", "ax_", "ay_"]:
        if col in df.columns:
            df[col] = np.nan

    if {"nose_x", "nose_y", "left_ear_x", "left_ear_y", "right_ear_x", "right_ear_y"}.issubset(df.columns):
        updated_cells += set_col(df, "angle_", df.apply(calc_head_angle, axis=1))

    rigid_columns = {
        "rigid_nose_x", "rigid_nose_y",
        "rigid_left_ear_x", "rigid_left_ear_y",
        "rigid_right_ear_x", "rigid_right_ear_y",
    }
    if rigid_columns.issubset(df.columns):
        rigid_angles = df.apply(lambda row: calc_head_angle(row, "rigid_"), axis=1)
        updated_cells += set_col(df, "rigid_head_angle_rad", rigid_angles)
        updated_cells += set_col(df, "rigid_head_angle_deg", np.degrees(rigid_angles))

    updated_cells += update_screen_columns(df, screen_start_x, screen_pix_cm, screen_y)

    if is_parquet:
        df.to_parquet(pose_path, index=False)
    else:
        df.to_csv(pose_path, index=False)

    log(f"Updated calibrated pose columns in {pose_path}")
    return {
        "output_path": str(pose_path),
        "updated_cells": updated_cells,
        "cam_name": cam_name,
        "calibration_dir": str(Path(calibration_dir).expanduser()),
        "screen_start_x": screen_start_x,
        "screen_pix_cm": screen_pix_cm,
        "screen_y": screen_y,
    }


def main():
    parser = argparse.ArgumentParser(description="Recompute calibrated pose columns for an edited DLC pose file.")
    parser.add_argument("--pose-file", required=True)
    parser.add_argument("--video-path", required=True)
    parser.add_argument("--calibration-dir", required=True)
    parser.add_argument("--start-x", type=float, default=None)
    parser.add_argument("--pix-cm", type=float, default=None)
    parser.add_argument("--screen-y", type=float, default=None)
    args = parser.parse_args()
    result = run_edited_pose_calibration_job(
        pose_file=args.pose_file,
        video_path=args.video_path,
        calibration_dir=args.calibration_dir,
        screen_start_x=args.start_x,
        screen_pix_cm=args.pix_cm,
        screen_y=args.screen_y,
        logger=print,
    )
    print(result)


if __name__ == "__main__":
    main()
